package com.share.shamir.dal.mapper;

import com.share.shamir.dal.entity.Shamir;

import java.util.List;

public interface ShamirMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shamir
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shamir
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int insert(Shamir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shamir
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int insertSelective(Shamir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shamir
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    Shamir selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shamir
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int updateByPrimaryKeySelective(Shamir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shamir
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int updateByPrimaryKey(Shamir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shamir
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    List<Shamir> selectByShamirId(String shamirId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shamir
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    List<Shamir> selectByShamirUserKey(Integer ShamirUserKey);
}