package com.share.shamir.dal.mapper;

import com.share.shamir.dal.entity.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int insertSelective(User record);

    User selectByUserName(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    User selectByPrimaryKey(Integer id);

    List<User> selectUserByRole(String role);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    int updateByPrimaryKey(User record);
}