package com.share.shamir.dal.entity;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.address
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.phone
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.email
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.count
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization
     *
     * @return the value of organization.organization
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization
     *
     * @param organization the value for organization.organization
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.address
     *
     * @return the value of organization.address
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.address
     *
     * @param address the value for organization.address
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.phone
     *
     * @return the value of organization.phone
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.phone
     *
     * @param phone the value for organization.phone
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.email
     *
     * @return the value of organization.email
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.email
     *
     * @param email the value for organization.email
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.count
     *
     * @return the value of organization.count
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.count
     *
     * @param count the value for organization.count
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}