package com.share.shamir.dal.entity;

public class Shamir {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shamir.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shamir.shamirId
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String shamirid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shamir.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String shamirkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shamir.shamirUserKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private Integer shamiruserkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shamir.id
     *
     * @return the value of shamir.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shamir.id
     *
     * @param id the value for shamir.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shamir.shamirId
     *
     * @return the value of shamir.shamirId
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getShamirid() {
        return shamirid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shamir.shamirId
     *
     * @param shamirid the value for shamir.shamirId
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setShamirid(String shamirid) {
        this.shamirid = shamirid == null ? null : shamirid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shamir.shamirKey
     *
     * @return the value of shamir.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getShamirkey() {
        return shamirkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shamir.shamirKey
     *
     * @param shamirkey the value for shamir.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setShamirkey(String shamirkey) {
        this.shamirkey = shamirkey == null ? null : shamirkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shamir.shamirUserKey
     *
     * @return the value of shamir.shamirUserKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public Integer getShamiruserkey() {
        return shamiruserkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shamir.shamirUserKey
     *
     * @param shamiruserkey the value for shamir.shamirUserKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setShamiruserkey(Integer shamiruserkey) {
        this.shamiruserkey = shamiruserkey;
    }
}