package com.share.shamir.dal.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shamirId
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String shamirid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String shamirkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String fhe_pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String fhe_sk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String ecc_sk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    private String ecc_pk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user_id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param user_id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shamirId
     *
     * @return the value of user.shamirId
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getShamirid() {
        return shamirid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shamirId
     *
     * @param shamirid the value for user.shamirId
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setShamirid(String shamirid) {
        this.shamirid = shamirid == null ? null : shamirid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shamirKey
     *
     * @return the value of user.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public String getShamirkey() {
        return shamirkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shamirKey
     *
     * @param shamirkey the value for user.shamirKey
     *
     * @mbggenerated Tue Nov 01 14:30:43 CST 2022
     */
    public void setShamirkey(String shamirkey) {
        this.shamirkey = shamirkey == null ? null : shamirkey.trim();
    }

    public void setFhe_pk(String fhe_pk) {
        this.fhe_pk = fhe_pk;
    }

    public String getFhe_pk() {
        return fhe_pk;
    }

    public void setEcc_sk(String ecc_sk) {
        this.ecc_sk = ecc_sk;
    }

    public String getEcc_sk() {
        return ecc_sk;
    }

    public void setEcc_pk(String ecc_pk) {
        this.ecc_pk = ecc_pk;
    }

    public String getEcc_pk() {
        return ecc_pk;
    }

    public void setFhe_sk(String fhe_sk) {
        this.fhe_sk = fhe_sk;
    }

    public String getFhe_sk() {
        return fhe_sk;
    }
}