version: "3"

services:
  shamir:
    image: hushaozhou/shamir:latest
    ports:
      - "8087:8080"
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001"
      - "4001:4001"
      - "8080:8080"
    restart: always